FROM node:alpine
# use alpie linux distribution 
COPY . /app
# copy all files in currnt directory to the app directory into tht img called app
WORKDIR / app
#working directory
CMD node app.js 
# command instruction to execute the command 